@startuml Decopy

' クラス定義
package Decopy{
    Package Content {
        class ContentManager {
            --
            + {static} createContent
            + {static} output
        }
        ' Decoratorパターン ここから ---
        abstract class Content {
            --
            + {abstract} getColumns
            + {abstract} getRows
            + {abstract} getRowText
        }

        class TextContent extends Content {
            - text
            --
            + getColumns
            + getRows
            + getRowText
        }

        abstract class Border extends Content {
            # content
        }

        class LeftBorder extends Border {
            --
            + getColumns
            + getRows
            + getRowText
        }

        class UpDownBorder extends Border {
            --
            + getColumns
            + getRows
            + getRowText
        }
        ' Decoratorパターン ここまで---
    }

    package UI {
        class DecopyInputController implements ActionListener{
            --
            + displayDecopyInputFrame
            + actionPerformed
        }

        class DecopyInputFrame extends Frame{
            - choiceOfPlacement
            - textFieldOfCharacter
            --
            + DecopyInputFrame(DecopyInputController)
            + getDecopyInput
            + setActionListener
        }

        class DecopyInput{
        - placement
        - decoString
        --
        + setter
        + getter
        }
    }

    package util {
        class ClipboardController {
        --
        + {static} pull
        + {static} push
        }
    }

    class Decopy {
        --
        ' - {static} isPlacement
        ' - {static} createContet
        ' - {static} output
        - {static} usage
    }
}

' クラス間の関係
left to right direction
Decopy .> DecopyInputController
Content --o Border 
ContentManager ..> ClipboardController
DecopyInputController ..> ContentManager
ContentManager .> Content
DecopyInputController .> DecopyInputFrame
DecopyInputController .> DecopyInput
DecopyInputFrame .> DecopyInput


@enduml
