@startuml Decopy

title Decopy main sequence
hide footbox
autonumber

actor User as u
participant Decopy as d #LightSalmon
participant DecopyInputController as dic #Yellow
participant DecopyInputFrame as dif #LightYellow
participant ContentManager as cm #LightCyan
participant ClipboardController as cbc

u -> d: run
activate d
d -> dic: displayDecopyInputFrame
activate dic
deactivate d
dic -> dif: DecopyInputFrame(self)
activate dif
u -> dif: input information
dif -> dic: actionPerformed
deactivate dif
dic -> cm: output(creatContent)
activate cm
deactivate dic
cm -> cbc: pull/push

@enduml